### ISSUE TITLE
can not route to / if prefix is given

### ISSUE THREAD

**Issue by orangemi** [toajs/toa-router#5]
I think this change break the route for `/` if prefix is given
https://github.com/toajs/toa-router/blob/master/index.js#L19
```javascript
if (!this.root.endsWith('/')) this.root += '/'
```
And this line will never pass if only visit the prefix route.
https://github.com/toajs/toa-router/blob/master/index.js#L54

Example code:
```javascript
const toa = require('toa')
const Router = require('toa-router')
const router = new Router('/abc')
const app = toa()

router.get('/', function * () {
  this.body = 'ok'
})

app.use(router.toThunk())
app.listen(3001)
```

Try to visit `http://localhost:3001/abc`

**Comment by zensh** [comment]
`v2.1.3`
